# Generated by Django 5.2.5 on 2025-08-23 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_limited_to_price', models.BooleanField(default=False)),
                ('minimum_price_to_cover', models.IntegerField(null=True)),
                ('maximum_price_to_cover', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_time', models.PositiveIntegerField(default=24, help_text='in hours', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_available', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='Products.category')),
                ('images', models.ManyToManyField(to='Products.productimage')),
            ],
        ),
    ]
